site_name: cargs
site_description: Modern C library for command-line argument parsing
site_url: https://cargs.readthedocs.io
site_author: lucocozz
repo_name: lucocozz/cargs
repo_url: https://github.com/lucocozz/cargs
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 lucocozz

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Basic Options: guide/basic-options.md
    - Subcommands: guide/subcommands.md
    - Validation: guide/validation.md
    - Environment Variables: guide/environment.md
  - API Reference:
    - Overview: api/overview.md
    - Types: api/types.md
    - Macros: api/macros.md
    - Functions: api/functions.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Subcommands: examples/subcommands.md
    - Positional Arguments: examples/positional.md
    - Multi-Values: examples/multi-values.md
    - Validations: examples/validators.md
  - Advanced:
    - Custom Handlers: advanced/custom-handlers.md
    - Regular Expressions: advanced/regex.md
    - Nested Commands: advanced/nested-commands.md
  - Contributing: contributing.md
  - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucocozz/cargs
  generator: false
