site_name: cargs
site_description: Modern C library for command-line argument parsing
site_url: https://cargs.readthedocs.io
site_author: lucocozz
repo_name: lucocozz/cargs
repo_url: https://github.com/lucocozz/cargs
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 lucocozz

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - navigation.top
    - content.action.edit  
    - content.action.download
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "cargs"
        - locale: fr
          name: Français
          build: true
          site_name: "cargs"
      default_language: en
      no_translation: "This page is not available in your language."
      languages_dirs:
        en: en
        fr: fr
      nav_translations:
        fr:
          Home: Accueil
          User Guide: Guide d'utilisation
          Installation: Installation
          Quick Start: Démarrage rapide
          Basic Options: Options de base
          Multi Values Options: Options multi-valeurs
          Option Formats: Formats d'options
          Subcommands: Sous-commandes
          Validation: Validation
          Environment Variables: Variables d'environnement
          API Reference: Référence API
          Overview: Aperçu
          Functions: Fonctions
          Macros: Macros
          Types: Types
          Regex Patterns: Motifs Regex
          Examples: Exemples
          Basic Usage: Utilisation de base
          Positional Arguments: Arguments positionnels
          Validations: Validations
          Advanced: Avancé
          Custom Handlers: Gestionnaires personnalisés
          Custom Validators: Validateurs personnalisés
          Regular Expressions: Expressions régulières
          Nested Commands: Commandes imbriquées
          Multi-Values: Multi-valeurs
          Contributing: Contribuer
          License: Licence
          # Misc: Divers

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: document
          class: document
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucocozz/cargs
  generator: false

docs_dir: docs

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Basic Options: guide/basic-options.md
    - Multi Values Options: guide/multi-values.md
    - Option Formats: guide/option-formats.md
    - Subcommands: guide/subcommands.md
    - Validation: guide/validation.md
    - Environment Variables: guide/environment.md
  - API Reference:
    - Overview: api/overview.md
    - Functions: api/functions.md
    - Macros: api/macros.md
    - Types: api/types.md
    - Regex Patterns: api/regex_patterns.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Subcommands: examples/subcommands.md
    - Positional Arguments: examples/positional.md
    - Multi-Values: examples/multi-values.md
    - Validations: examples/validators.md
  - Advanced:
    - Custom Handlers: advanced/custom-handlers.md
    - Custom Validators: advanced/custom-validators.md
    - Regular Expressions: advanced/regex.md
    - Nested Commands: advanced/nested-commands.md
    - Multi-Values: advanced/multi-values.md
  - Contributing: contributing.md
  - License: license.md
  # - Misc:
    # - llm reference: misc/llm-references.md
    # - FAQ: misc/faq.md
    # - Changelog: misc/changelog.md
    # - Roadmap: misc/roadmap.md
