blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/lucocozz/cargs/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/lucocozz/cargs#readme
    about: Check the documentation before opening an issue.
