name: CI Complete

on:
  workflow_run:
    workflows: ["Test", "Examples"]
    types:
      - completed

jobs:
  ci-complete:
    name: Pipeline Status Report
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow results
        run: |
          echo "Checking CI workflows status..."
          
          # Get status of previous workflows
          quality_status="${{ github.event.workflow_run.conclusion }}"
          test_status="${{ github.event.workflow_run.conclusion }}"
          examples_status="${{ github.event.workflow_run.conclusion }}"
          
          # Display status of each step
          echo "Quality Analysis: $quality_status"
          echo "Build: Checked by dependency"
          echo "Tests: $test_status"
          echo "Examples: $examples_status"
          
          # Check if all workflows succeeded
          if [ "$quality_status" = "success" ] && [ "$test_status" = "success" ] && [ "$examples_status" = "success" ]; then
            echo "✅ All CI checks have passed successfully!"
            exit 0
          else
            echo "❌ One or more CI checks have failed."
            exit 1
          fi
          
      - name: Create status badge
        if: success()
        run: echo "CI_STATUS=passing" >> $GITHUB_ENV
        
      - name: Update status badge (failing)
        if: failure()
        run: echo "CI_STATUS=failing" >> $GITHUB_ENV