name: PR Issue Check

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-for-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR references an issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const title = pr.title || '';
            
            // Check for issue references in PR body
            const issueRefs = body.match(/(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/gi);
            
            // List of users who can bypass this check
            const bypassUsers = ['lucocozz']; // Add your GitHub username
            
            // Special title prefixes that can bypass the check
            const bypassPrefixes = ['[no-issue]', '[trivial]', '[hotfix]'];
            
            // Check for bypass conditions
            const userBypass = bypassUsers.includes(pr.user.login);
            const prefixBypass = bypassPrefixes.some(prefix => 
              title.toLowerCase().startsWith(prefix.toLowerCase())
            );
            
            // Log the status
            console.log(`PR by: ${pr.user.login}`);
            console.log(`PR title: ${title}`);
            console.log(`User bypass: ${userBypass}`);
            console.log(`Prefix bypass: ${prefixBypass}`);
            console.log(`Issue reference: ${issueRefs ? 'Yes' : 'No'}`);
            
            // Skip check for your username or bypassed prefixes
            if (userBypass) {
              console.log("✅ Check skipped: PR author is in bypass list");
              return;
            }
            
            if (prefixBypass) {
              console.log("✅ Check skipped: PR title has bypass prefix");
              return;
            }
            
            // Fail if no issue references found for non-bypassed PRs
            if (!issueRefs) {
              core.setFailed("This PR doesn't reference an issue. Please either:\n" +
                             "1. Reference an issue with 'Fixes #NUMBER' in the PR description\n" +
                             "2. Use one of these prefixes in PR title: [no-issue], [trivial], [hotfix]");
            } else {
              console.log("✅ PR references an issue");
            }
