name: Create Release Package

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libpcre2-dev
      
      - name: Build library
        run: |
          meson setup -Dbuildtype=release .build
          meson compile -C .build
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Create package with installer
        run: |
          mkdir -p cargs-${{ env.VERSION }}/include
          mkdir -p cargs-${{ env.VERSION }}/lib

          cp -r includes/* cargs-${{ env.VERSION }}/include/
          cp .build/libcargs.a cargs-${{ env.VERSION }}/lib/
          cp .build/libcargs.so.${{ env.VERSION }} cargs-${{ env.VERSION }}/lib/

          cp packaging/installers/install.sh cargs-${{ env.VERSION }}/
          chmod +x cargs-${{ env.VERSION }}/install.sh

          cp README.md LICENSE cargs-${{ env.VERSION }}/

          tar -czf cargs-${{ env.VERSION }}.tar.gz cargs-${{ env.VERSION }}
          zip -r cargs-${{ env.VERSION }}.zip cargs-${{ env.VERSION }}
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cargs-${{ env.VERSION }}.tar.gz
            cargs-${{ env.VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
